//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8825
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinovea.Updater.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UpdaterLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdaterLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kinovea.Updater.Languages.UpdaterLang", typeof(UpdaterLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Update….
        /// </summary>
        public static string mnuCheckForUpdates {
            get {
                return ResourceManager.GetString("mnuCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available!.
        /// </summary>
        public static string Updater_Behind {
            get {
                return ResourceManager.GetString("Updater_Behind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the target directory for the installer file..
        /// </summary>
        public static string Updater_BrowseFolderDescription {
            get {
                return ResourceManager.GetString("Updater_BrowseFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version :.
        /// </summary>
        public static string Updater_CurrentVersion {
            get {
                return ResourceManager.GetString("Updater_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Updater_Download {
            get {
                return ResourceManager.GetString("Updater_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size :.
        /// </summary>
        public static string Updater_FileSize {
            get {
                return ResourceManager.GetString("Updater_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking for updates. Please ensure an Internet connection is available. .
        /// </summary>
        public static string Updater_InternetError {
            get {
                return ResourceManager.GetString("Updater_InternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log :.
        /// </summary>
        public static string Updater_LblChangeLog {
            get {
                return ResourceManager.GetString("Updater_LblChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new version was successfully downloaded.\n Please close Kinovea and launch the installer from where you saved it. .
        /// </summary>
        public static string Updater_mboxDownloadSuccess_Description {
            get {
                return ResourceManager.GetString("Updater_mboxDownloadSuccess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string Updater_MegaBytes {
            get {
                return ResourceManager.GetString("Updater_MegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version.
        /// </summary>
        public static string Updater_NewVersion {
            get {
                return ResourceManager.GetString("Updater_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Updater_Quit {
            get {
                return ResourceManager.GetString("Updater_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinovea - Checking for new version..
        /// </summary>
        public static string Updater_Title {
            get {
                return ResourceManager.GetString("Updater_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version is up to date !.
        /// </summary>
        public static string Updater_UpToDate {
            get {
                return ResourceManager.GetString("Updater_UpToDate", resourceCulture);
            }
        }
    }
}
