//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinovea.Root.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RootLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RootLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kinovea.Root.Languages.RootLang", typeof(RootLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building blocks.
        /// </summary>
        public static string dlgAbout_BuildingBlocks {
            get {
                return ResourceManager.GetString("dlgAbout_BuildingBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citation.
        /// </summary>
        public static string dlgAbout_Citation {
            get {
                return ResourceManager.GetString("dlgAbout_Citation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string dlgAbout_License {
            get {
                return ResourceManager.GetString("dlgAbout_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string dlgAbout_Translation {
            get {
                return ResourceManager.GetString("dlgAbout_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable audio trigger.
        /// </summary>
        public static string dlgPreferences_Capture_chkEnableAudioTrigger {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_chkEnableAudioTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore file overwrite warning.
        /// </summary>
        public static string dlgPreferences_Capture_chkIgnoreOverwrite {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_chkIgnoreOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record uncompressed video.
        /// </summary>
        public static string dlgPreferences_Capture_chkUncompressedVideo {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_chkUncompressedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string dlgPreferences_Capture_Context {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context variables.
        /// </summary>
        public static string dlgPreferences_Capture_ContextVariables {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_ContextVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string dlgPreferences_Capture_File {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High speed cameras.
        /// </summary>
        public static string dlgPreferences_Capture_gbHighspeedCameras {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_gbHighspeedCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image naming.
        /// </summary>
        public static string dlgPreferences_Capture_ImageNaming {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_ImageNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display framerate (fps):.
        /// </summary>
        public static string dlgPreferences_Capture_lblForcedFramerate {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_lblForcedFramerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image format:.
        /// </summary>
        public static string dlgPreferences_Capture_lblImageFormat {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_lblImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input device:.
        /// </summary>
        public static string dlgPreferences_Capture_lblInputDevice {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_lblInputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocated for delay buffers: {0} MB..
        /// </summary>
        public static string dlgPreferences_Capture_lblMemoryBuffer {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_lblMemoryBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post recording command:.
        /// </summary>
        public static string dlgPreferences_Capture_lblPostRecordingCommand {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_lblPostRecordingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate replacement threshold (fps):.
        /// </summary>
        public static string dlgPreferences_Capture_lblReplacementThreshold {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_lblReplacementThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement framerate (fps):.
        /// </summary>
        public static string dlgPreferences_Capture_lblReplacementValue {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_lblReplacementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording by duration (s):.
        /// </summary>
        public static string dlgPreferences_Capture_lblStopRecordingByDuration {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_lblStopRecordingByDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger threshold:.
        /// </summary>
        public static string dlgPreferences_Capture_lblTriggerThreshold {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_lblTriggerThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncompressed video format:.
        /// </summary>
        public static string dlgPreferences_Capture_lblUncompressedVideoFormat {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_lblUncompressedVideoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video format:.
        /// </summary>
        public static string dlgPreferences_Capture_lblVideoFormat {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_lblVideoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string dlgPreferences_Capture_Left {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro.
        /// </summary>
        public static string dlgPreferences_Capture_Macro {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera alias.
        /// </summary>
        public static string dlgPreferences_Capture_PatternCameraAlias {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternCameraAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture directory.
        /// </summary>
        public static string dlgPreferences_Capture_PatternCaptureDirectory {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternCaptureDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured file name.
        /// </summary>
        public static string dlgPreferences_Capture_PatternCaptureFilename {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternCaptureFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured framerate.
        /// </summary>
        public static string dlgPreferences_Capture_PatternConfiguredFramerate {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternConfiguredFramerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (YYYYMMDD).
        /// </summary>
        public static string dlgPreferences_Capture_PatternDate {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time (YYYYMMDD-HHMMSS).
        /// </summary>
        public static string dlgPreferences_Capture_PatternDateTime {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string dlgPreferences_Capture_PatternDay {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape sequence.
        /// </summary>
        public static string dlgPreferences_Capture_PatternEscape {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string dlgPreferences_Capture_PatternHour {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string dlgPreferences_Capture_PatternMinute {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string dlgPreferences_Capture_PatternMonth {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received framerate.
        /// </summary>
        public static string dlgPreferences_Capture_PatternReceivedFramerate {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternReceivedFramerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string dlgPreferences_Capture_PatternSecond {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (HHMMSS).
        /// </summary>
        public static string dlgPreferences_Capture_PatternTime {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string dlgPreferences_Capture_PatternYear {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_PatternYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string dlgPreferences_Capture_Recording {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording mode and delay.
        /// </summary>
        public static string dlgPreferences_Capture_RecordingMode {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_RecordingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera: records real time frames..
        /// </summary>
        public static string dlgPreferences_Capture_RecordingMode_Camera {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_RecordingMode_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed: records delayed frames..
        /// </summary>
        public static string dlgPreferences_Capture_RecordingMode_Display {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_RecordingMode_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retroactive: records frames when the capture stops..
        /// </summary>
        public static string dlgPreferences_Capture_RecordingMode_Scheduled {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_RecordingMode_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string dlgPreferences_Capture_Right {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root:.
        /// </summary>
        public static string dlgPreferences_Capture_Root {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub directory:.
        /// </summary>
        public static string dlgPreferences_Capture_Subdir {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_Subdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string dlgPreferences_Capture_tabAutomation {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_tabAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string dlgPreferences_Capture_tabMemory {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_tabMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video naming.
        /// </summary>
        public static string dlgPreferences_Capture_VideoNaming {
            get {
                return ResourceManager.GetString("dlgPreferences_Capture_VideoNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable custom tools debug mode.
        /// </summary>
        public static string dlgPreferences_Drawings_chkCustomToolsDebugMode {
            get {
                return ResourceManager.GetString("dlgPreferences_Drawings_chkCustomToolsDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show drawings when video is playing.
        /// </summary>
        public static string dlgPreferences_Drawings_chkDrawOnPlay {
            get {
                return ResourceManager.GetString("dlgPreferences_Drawings_chkDrawOnPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable coordinates filtering.
        /// </summary>
        public static string dlgPreferences_Drawings_chkEnableFiltering {
            get {
                return ResourceManager.GetString("dlgPreferences_Drawings_chkEnableFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default opacity of new drawings:.
        /// </summary>
        public static string dlgPreferences_Drawings_lblDefaultOpacity {
            get {
                return ResourceManager.GetString("dlgPreferences_Drawings_lblDefaultOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, drawings will stay visible for {0} images around the Key Image..
        /// </summary>
        public static string dlgPreferences_Drawings_lblFading {
            get {
                return ResourceManager.GetString("dlgPreferences_Drawings_lblFading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible for the entire video.
        /// </summary>
        public static string dlgPreferences_Drawings_rbAlwaysVisible {
            get {
                return ResourceManager.GetString("dlgPreferences_Drawings_rbAlwaysVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow multiple instances of Kinovea.
        /// </summary>
        public static string dlgPreferences_General_chkAllowMultipleInstances {
            get {
                return ResourceManager.GetString("dlgPreferences_General_chkAllowMultipleInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instances have their own preferences.
        /// </summary>
        public static string dlgPreferences_General_InstancesHaveOwnPreferences {
            get {
                return ResourceManager.GetString("dlgPreferences_General_InstancesHaveOwnPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of files in history:.
        /// </summary>
        public static string dlgPreferences_General_lblHistoryCount {
            get {
                return ResourceManager.GetString("dlgPreferences_General_lblHistoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string dlgPreferences_Keyboard_btnApply {
            get {
                return ResourceManager.GetString("dlgPreferences_Keyboard_btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string dlgPreferences_Keyboard_btnClear {
            get {
                return ResourceManager.GetString("dlgPreferences_Keyboard_btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string dlgPreferences_Keyboard_btnDefault {
            get {
                return ResourceManager.GetString("dlgPreferences_Keyboard_btnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string dlgPreferences_Keyboard_lblCategories {
            get {
                return ResourceManager.GetString("dlgPreferences_Keyboard_lblCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string dlgPreferences_Keyboard_lblCommands {
            get {
                return ResourceManager.GetString("dlgPreferences_Keyboard_lblCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey for {0}.{1}.
        /// </summary>
        public static string dlgPreferences_Keyboard_lblHotkey {
            get {
                return ResourceManager.GetString("dlgPreferences_Keyboard_lblHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always deinterlace when opening a new video.
        /// </summary>
        public static string dlgPreferences_Player_DeinterlaceByDefault {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_DeinterlaceByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Analysis mode.
        /// </summary>
        public static string dlgPreferences_Player_GroupAnalysisMode {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_GroupAnalysisMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import image sequences as videos.
        /// </summary>
        public static string dlgPreferences_Player_ImportImageSequences {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_ImportImageSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update image during time cursor movement.
        /// </summary>
        public static string dlgPreferences_Player_InteractiveFrameTracker {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_InteractiveFrameTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default aspect ratio:.
        /// </summary>
        public static string dlgPreferences_Player_lblImageFormat {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_lblImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string dlgPreferences_Player_lblLanguages {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_lblLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string dlgPreferences_Player_lblLogicAnd {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_lblLogicAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache memory allocated to each playback screen: {0} MB..
        /// </summary>
        public static string dlgPreferences_Player_lblMemory {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_lblMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link speed sliders when comparing videos.
        /// </summary>
        public static string dlgPreferences_Player_SyncLockSpeeds {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_SyncLockSpeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string dlgPreferences_Player_tabUnits {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_tabUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string dlgPreferences_Player_Tracking {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default tracking parameters.
        /// </summary>
        public static string dlgPreferences_Player_TrackingDescription {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_TrackingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object window:.
        /// </summary>
        public static string dlgPreferences_Player_TrackingObjectWindow {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_TrackingObjectWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string dlgPreferences_Player_TrackingPercentage {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_TrackingPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixels.
        /// </summary>
        public static string dlgPreferences_Player_TrackingPixels {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_TrackingPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search window:.
        /// </summary>
        public static string dlgPreferences_Player_TrackingSearchWindow {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_TrackingSearchWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration:.
        /// </summary>
        public static string dlgPreferences_Player_UnitsAcceleration {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle:.
        /// </summary>
        public static string dlgPreferences_Player_UnitsAngle {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angular acceleration:.
        /// </summary>
        public static string dlgPreferences_Player_UnitsAngularAcceleration {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsAngularAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angular velocity:.
        /// </summary>
        public static string dlgPreferences_Player_UnitsAngularVelocity {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsAngularVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom length unit :.
        /// </summary>
        public static string dlgPreferences_Player_UnitsCustom {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees ({0}).
        /// </summary>
        public static string dlgPreferences_Player_UnitsDegrees {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees per second ({0}).
        /// </summary>
        public static string dlgPreferences_Player_UnitsDegreesPerSecond {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsDegreesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees per second squared ({0}).
        /// </summary>
        public static string dlgPreferences_Player_UnitsDegreesPerSecondSquared {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsDegreesPerSecondSquared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet per second squared ({0}).
        /// </summary>
        public static string dlgPreferences_Player_UnitsFeetPerSecondSquared {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsFeetPerSecondSquared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters per second squared ({0}).
        /// </summary>
        public static string dlgPreferences_Player_UnitsMetersPerSecondSquared {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsMetersPerSecondSquared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radians ({0}).
        /// </summary>
        public static string dlgPreferences_Player_UnitsRadians {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsRadians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radians per second ({0}).
        /// </summary>
        public static string dlgPreferences_Player_UnitsRadiansPerSecond {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsRadiansPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radians per second squared ({0}).
        /// </summary>
        public static string dlgPreferences_Player_UnitsRadiansPerSecondSquared {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsRadiansPerSecondSquared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolutions per minute ({0}).
        /// </summary>
        public static string dlgPreferences_Player_UnitsRevolutionsPerMinute {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsRevolutionsPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        public static string dlgPreferences_Player_UnitsSpeed {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitsSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string dlgPreferences_Player_UnitTime {
            get {
                return ResourceManager.GetString("dlgPreferences_Player_UnitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet per second ({0}).
        /// </summary>
        public static string dlgPreferences_Speed_FeetPerSecond {
            get {
                return ResourceManager.GetString("dlgPreferences_Speed_FeetPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers per hour ({0}).
        /// </summary>
        public static string dlgPreferences_Speed_KilometersPerHour {
            get {
                return ResourceManager.GetString("dlgPreferences_Speed_KilometersPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters per second ({0}).
        /// </summary>
        public static string dlgPreferences_Speed_MetersPerSecond {
            get {
                return ResourceManager.GetString("dlgPreferences_Speed_MetersPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles per hour ({0}).
        /// </summary>
        public static string dlgPreferences_Speed_MilesPerHour {
            get {
                return ResourceManager.GetString("dlgPreferences_Speed_MilesPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string dlgPreferences_tabCapture {
            get {
                return ResourceManager.GetString("dlgPreferences_tabCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawings.
        /// </summary>
        public static string dlgPreferences_tabDrawings {
            get {
                return ResourceManager.GetString("dlgPreferences_tabDrawings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string dlgPreferences_tabGeneral {
            get {
                return ResourceManager.GetString("dlgPreferences_tabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string dlgPreferences_tabKeyboard {
            get {
                return ResourceManager.GetString("dlgPreferences_tabKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string dlgPreferences_tabPlayback {
            get {
                return ResourceManager.GetString("dlgPreferences_tabPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string dlgPreferences_Title {
            get {
                return ResourceManager.GetString("dlgPreferences_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the user interface….
        /// </summary>
        public static string dlgSplash_LoadInfos {
            get {
                return ResourceManager.GetString("dlgSplash_LoadInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Generic_Quit {
            get {
                return ResourceManager.GetString("Generic_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Generic_Save {
            get {
                return ResourceManager.GetString("Generic_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Kinovea….
        /// </summary>
        public static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log folder….
        /// </summary>
        public static string mnuApplicationFolder {
            get {
                return ResourceManager.GetString("mnuApplicationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string mnuEdit {
            get {
                return ResourceManager.GetString("mnuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string mnuFile {
            get {
                return ResourceManager.GetString("mnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen.
        /// </summary>
        public static string mnuFullScreen {
            get {
                return ResourceManager.GetString("mnuFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string mnuHelp {
            get {
                return ResourceManager.GetString("mnuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinovea help....
        /// </summary>
        public static string mnuHelpContents {
            get {
                return ResourceManager.GetString("mnuHelpContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string mnuHistory {
            get {
                return ResourceManager.GetString("mnuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset history.
        /// </summary>
        public static string mnuHistoryReset {
            get {
                return ResourceManager.GetString("mnuHistoryReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string mnuImage {
            get {
                return ResourceManager.GetString("mnuImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string mnuLanguages {
            get {
                return ResourceManager.GetString("mnuLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string mnuOptions {
            get {
                return ResourceManager.GetString("mnuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences….
        /// </summary>
        public static string mnuPreferences {
            get {
                return ResourceManager.GetString("mnuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string mnuRedo {
            get {
                return ResourceManager.GetString("mnuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string mnuScreens {
            get {
                return ResourceManager.GetString("mnuScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string mnuTimeFormat {
            get {
                return ResourceManager.GetString("mnuTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string mnuTools {
            get {
                return ResourceManager.GetString("mnuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string mnuUndo {
            get {
                return ResourceManager.GetString("mnuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string mnuVideo {
            get {
                return ResourceManager.GetString("mnuVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame number.
        /// </summary>
        public static string TimeCodeFormat_Frames {
            get {
                return ResourceManager.GetString("TimeCodeFormat_Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundredth of a minute.
        /// </summary>
        public static string TimeCodeFormat_HundredthOfMinutes {
            get {
                return ResourceManager.GetString("TimeCodeFormat_HundredthOfMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total microseconds.
        /// </summary>
        public static string TimeCodeFormat_Microseconds {
            get {
                return ResourceManager.GetString("TimeCodeFormat_Microseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total milliseconds.
        /// </summary>
        public static string TimeCodeFormat_Milliseconds {
            get {
                return ResourceManager.GetString("TimeCodeFormat_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten thousandth of an hour.
        /// </summary>
        public static string TimeCodeFormat_TenThousandthOfHours {
            get {
                return ResourceManager.GetString("TimeCodeFormat_TenThousandthOfHours", resourceCulture);
            }
        }
    }
}
