//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinovea.FileBrowser.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileBrowserLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileBrowserLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kinovea.FileBrowser.Languages.FileBrowserLang", typeof(FileBrowserLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget custom settings.
        /// </summary>
        internal static string ForgetCustomSettings {
            get {
                return ResourceManager.GetString("ForgetCustomSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera type.
        /// </summary>
        internal static string FormCameraWizard_CameraType {
            get {
                return ResourceManager.GetString("FormCameraWizard_CameraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create camera.
        /// </summary>
        internal static string FormCameraWizard_Create {
            get {
                return ResourceManager.GetString("FormCameraWizard_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string FormCameraWizard_Parameters {
            get {
                return ResourceManager.GetString("FormCameraWizard_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string FormCameraWizard_Test {
            get {
                return ResourceManager.GetString("FormCameraWizard_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual connection.
        /// </summary>
        internal static string FormCameraWizard_Title {
            get {
                return ResourceManager.GetString("FormCameraWizard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Generic_Open {
            get {
                return ResourceManager.GetString("Generic_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras.
        /// </summary>
        internal static string lblCameras {
            get {
                return ResourceManager.GetString("lblCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture history.
        /// </summary>
        internal static string lblCaptureHistory {
            get {
                return ResourceManager.GetString("lblCaptureHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string lblFolders {
            get {
                return ResourceManager.GetString("lblFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video files.
        /// </summary>
        internal static string lblVideoFiles {
            get {
                return ResourceManager.GetString("lblVideoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add shortcut.
        /// </summary>
        internal static string mnuAddShortcut {
            get {
                return ResourceManager.GetString("mnuAddShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to shortcuts.
        /// </summary>
        internal static string mnuAddToShortcuts {
            get {
                return ResourceManager.GetString("mnuAddToShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete shortcut.
        /// </summary>
        internal static string mnuDeleteShortcut {
            get {
                return ResourceManager.GetString("mnuDeleteShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string mnuSortBy {
            get {
                return ResourceManager.GetString("mnuSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string mnuSortBy_Ascending {
            get {
                return ResourceManager.GetString("mnuSortBy_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string mnuSortBy_Date {
            get {
                return ResourceManager.GetString("mnuSortBy_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string mnuSortBy_Descending {
            get {
                return ResourceManager.GetString("mnuSortBy_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string mnuSortBy_Name {
            get {
                return ResourceManager.GetString("mnuSortBy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string mnuSortBy_Size {
            get {
                return ResourceManager.GetString("mnuSortBy_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        internal static string mnuVideoDelete {
            get {
                return ResourceManager.GetString("mnuVideoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate in Windows Explorer .
        /// </summary>
        internal static string mnuVideoLocate {
            get {
                return ResourceManager.GetString("mnuVideoLocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string tabExplorer {
            get {
                return ResourceManager.GetString("tabExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        internal static string tabShortcuts {
            get {
                return ResourceManager.GetString("tabShortcuts", resourceCulture);
            }
        }
    }
}
