//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3053
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinovea.ScreenManager.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScreenManagerLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScreenManagerLang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kinovea.ScreenManager.Languages.ScreenManagerLang", typeof(ScreenManagerLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string _ {
            get {
                return ResourceManager.GetString("", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hide Thumbnails.
        /// </summary>
        internal static string btnHideThumbView {
            get {
                return ResourceManager.GetString("btnHideThumbView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Thumbnails.
        /// </summary>
        internal static string btnShowThumbView {
            get {
                return ResourceManager.GetString("btnShowThumbView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invert Video Positions.
        /// </summary>
        internal static string btnSwap_ToolTip {
            get {
                return ResourceManager.GetString("btnSwap_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synchronize Videos on the Current Frames.
        /// </summary>
        internal static string btnSync_ToolTip {
            get {
                return ResourceManager.GetString("btnSync_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go Back to Beginning for Both Videos.
        /// </summary>
        internal static string buttonGotoFirst_ToolTip {
            get {
                return ResourceManager.GetString("buttonGotoFirst_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jump to End for Both Videos.
        /// </summary>
        internal static string buttonGotoLast_ToolTip {
            get {
                return ResourceManager.GetString("buttonGotoLast_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Next Frame for Both Videos.
        /// </summary>
        internal static string buttonGotoNext_ToolTip {
            get {
                return ResourceManager.GetString("buttonGotoNext_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Previous Frame for Both Videos.
        /// </summary>
        internal static string buttonGotoPrevious_ToolTip {
            get {
                return ResourceManager.GetString("buttonGotoPrevious_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play | Pause Both Videos.
        /// </summary>
        internal static string buttonPlay_ToolTip {
            get {
                return ResourceManager.GetString("buttonPlay_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Screen for Capture.
        /// </summary>
        internal static string CommandAddCaptureScreen_FriendlyName {
            get {
                return ResourceManager.GetString("CommandAddCaptureScreen_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Stopwatch.
        /// </summary>
        internal static string CommandAddChrono_FriendlyName {
            get {
                return ResourceManager.GetString("CommandAddChrono_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Drawing.
        /// </summary>
        internal static string CommandAddDrawing_FriendlyName {
            get {
                return ResourceManager.GetString("CommandAddDrawing_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Screen for Playback.
        /// </summary>
        internal static string CommandAddPlayerScreen_FriendlyName {
            get {
                return ResourceManager.GetString("CommandAddPlayerScreen_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Drawing.
        /// </summary>
        internal static string CommandDeleteDrawing_FriendlyName {
            get {
                return ResourceManager.GetString("CommandDeleteDrawing_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove a Key Image.
        /// </summary>
        internal static string CommandDeleteKeyframe_FriendlyName {
            get {
                return ResourceManager.GetString("CommandDeleteKeyframe_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load Video.
        /// </summary>
        internal static string CommandLoadMovie_FriendlyName {
            get {
                return ResourceManager.GetString("CommandLoadMovie_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load Video.
        /// </summary>
        internal static string CommandLoadMovieInScreen_FriendlyName {
            get {
                return ResourceManager.GetString("CommandLoadMovieInScreen_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play Video.
        /// </summary>
        internal static string CommandPlayMovie_FriendlyName {
            get {
                return ResourceManager.GetString("CommandPlayMovie_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close Screen.
        /// </summary>
        internal static string CommandRemoveScreen_FriendlyName {
            get {
                return ResourceManager.GetString("CommandRemoveScreen_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Video.
        /// </summary>
        internal static string CommandSaveMovie_FriendlyName {
            get {
                return ResourceManager.GetString("CommandSaveMovie_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Screens.
        /// </summary>
        internal static string CommandShowScreen_FriendlyName {
            get {
                return ResourceManager.GetString("CommandShowScreen_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swap Screens.
        /// </summary>
        internal static string CommandSwapScreens_FriendlyName {
            get {
                return ResourceManager.GetString("CommandSwapScreens_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Common Controls.
        /// </summary>
        internal static string CommandToggleCommonControls_FriendlyName {
            get {
                return ResourceManager.GetString("CommandToggleCommonControls_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML (*.xml)|*.xml;.
        /// </summary>
        internal static string dlgColorProfile_FileFilter {
            get {
                return ResourceManager.GetString("dlgColorProfile_FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color Profile....
        /// </summary>
        internal static string dlgColorProfile_Title {
            get {
                return ResourceManager.GetString("dlgColorProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default Color Profile.
        /// </summary>
        internal static string dlgColorProfile_ToolTip_DefaultProfile {
            get {
                return ResourceManager.GetString("dlgColorProfile_ToolTip_DefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load color profile.
        /// </summary>
        internal static string dlgColorProfile_ToolTip_LoadProfile {
            get {
                return ResourceManager.GetString("dlgColorProfile_ToolTip_LoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save color Profile.
        /// </summary>
        internal static string dlgColorProfile_ToolTip_SaveProfile {
            get {
                return ResourceManager.GetString("dlgColorProfile_ToolTip_SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Always Show Label.
        /// </summary>
        internal static string dlgConfigureChrono_chkShowLabel {
            get {
                return ResourceManager.GetString("dlgConfigureChrono_chkShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Label :.
        /// </summary>
        internal static string dlgConfigureChrono_Label {
            get {
                return ResourceManager.GetString("dlgConfigureChrono_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure Stopwatch.
        /// </summary>
        internal static string dlgConfigureChrono_Title {
            get {
                return ResourceManager.GetString("dlgConfigureChrono_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure Drawing.
        /// </summary>
        internal static string dlgConfigureDrawing_Title {
            get {
                return ResourceManager.GetString("dlgConfigureDrawing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Always Visible.
        /// </summary>
        internal static string dlgConfigureFading_chkAlwaysVisible {
            get {
                return ResourceManager.GetString("dlgConfigureFading_chkAlwaysVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use default value.
        /// </summary>
        internal static string dlgConfigureFading_chkDefault {
            get {
                return ResourceManager.GetString("dlgConfigureFading_chkDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable persistence.
        /// </summary>
        internal static string dlgConfigureFading_chkEnable {
            get {
                return ResourceManager.GetString("dlgConfigureFading_chkEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} images..
        /// </summary>
        internal static string dlgConfigureFading_lblValue {
            get {
                return ResourceManager.GetString("dlgConfigureFading_lblValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure Persistence.
        /// </summary>
        internal static string dlgConfigureFading_Title {
            get {
                return ResourceManager.GetString("dlgConfigureFading_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of Divisions :.
        /// </summary>
        internal static string dlgConfigureGrids_Divisions {
            get {
                return ResourceManager.GetString("dlgConfigureGrids_Divisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure Grid.
        /// </summary>
        internal static string dlgConfigureGrids_Title {
            get {
                return ResourceManager.GetString("dlgConfigureGrids_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Real size of the segment :.
        /// </summary>
        internal static string dlgConfigureMeasure_lblRealSize {
            get {
                return ResourceManager.GetString("dlgConfigureMeasure_lblRealSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calibrate measure.
        /// </summary>
        internal static string dlgConfigureMeasure_Title {
            get {
                return ResourceManager.GetString("dlgConfigureMeasure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right-to-left motion.
        /// </summary>
        internal static string dlgConfigureMosaic_cbRightToLeft {
            get {
                return ResourceManager.GetString("dlgConfigureMosaic_cbRightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frequency :.
        /// </summary>
        internal static string dlgConfigureMosaic_LabelFrequencyRoot {
            get {
                return ResourceManager.GetString("dlgConfigureMosaic_LabelFrequencyRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of images : {0:0}..
        /// </summary>
        internal static string dlgConfigureMosaic_LabelImages {
            get {
                return ResourceManager.GetString("dlgConfigureMosaic_LabelImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mosaic of all images..
        /// </summary>
        internal static string dlgConfigureMosaic_radioFrequency {
            get {
                return ResourceManager.GetString("dlgConfigureMosaic_radioFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mosaic of key images..
        /// </summary>
        internal static string dlgConfigureMosaic_radioKeyframes {
            get {
                return ResourceManager.GetString("dlgConfigureMosaic_radioKeyframes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mosaic Mode.
        /// </summary>
        internal static string dlgConfigureMosaic_Title {
            get {
                return ResourceManager.GetString("dlgConfigureMosaic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of frames per second at capture time :\n(ex: 300).
        /// </summary>
        internal static string dlgConfigureSpeed_lblFPSCaptureTime {
            get {
                return ResourceManager.GetString("dlgConfigureSpeed_lblFPSCaptureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of frames per seconds at display time : {0:0.00} fps..
        /// </summary>
        internal static string dlgConfigureSpeed_lblFPSDisplayTime {
            get {
                return ResourceManager.GetString("dlgConfigureSpeed_lblFPSDisplayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Video is {0:0} times slower than original..
        /// </summary>
        internal static string dlgConfigureSpeed_lblSlowFactor {
            get {
                return ResourceManager.GetString("dlgConfigureSpeed_lblSlowFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure original speed.
        /// </summary>
        internal static string dlgConfigureSpeed_Title {
            get {
                return ResourceManager.GetString("dlgConfigureSpeed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        internal static string dlgConfigureSpeed_ToolTip_Reset {
            get {
                return ResourceManager.GetString("dlgConfigureSpeed_ToolTip_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show the Target Marker.
        /// </summary>
        internal static string dlgConfigureTrajectory_chkShowTarget {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_chkShowTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Key Images Titles.
        /// </summary>
        internal static string dlgConfigureTrajectory_chkShowTitles {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_chkShowTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Path.
        /// </summary>
        internal static string dlgConfigureTrajectory_chkShowTrajectory {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_chkShowTrajectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string dlgConfigureTrajectory_ExtraData_None {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_ExtraData_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speed.
        /// </summary>
        internal static string dlgConfigureTrajectory_ExtraData_Speed {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_ExtraData_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Distance.
        /// </summary>
        internal static string dlgConfigureTrajectory_ExtraData_TotalDistance {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_ExtraData_TotalDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Measurement:.
        /// </summary>
        internal static string dlgConfigureTrajectory_LabelExtraData {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_LabelExtraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode :.
        /// </summary>
        internal static string dlgConfigureTrajectory_lblMode {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_lblMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path.
        /// </summary>
        internal static string dlgConfigureTrajectory_ModeTrajectory {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_ModeTrajectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete Path.
        /// </summary>
        internal static string dlgConfigureTrajectory_RadioComplete {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_RadioComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path section around current image.
        /// </summary>
        internal static string dlgConfigureTrajectory_RadioFocus {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_RadioFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Label following the Path.
        /// </summary>
        internal static string dlgConfigureTrajectory_RadioLabel {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_RadioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinates system origin.
        /// </summary>
        internal static string dlgConfigureTrajectory_SetOrigin {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_SetOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Style :.
        /// </summary>
        internal static string dlgConfigureTrajectory_Style {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure Path.
        /// </summary>
        internal static string dlgConfigureTrajectory_Title {
            get {
                return ResourceManager.GetString("dlgConfigureTrajectory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of video.
        /// </summary>
        internal static string dlgDiapoExport_GroupDiapoType {
            get {
                return ResourceManager.GetString("dlgDiapoExport_GroupDiapoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration on each Key Image : {0} hundredth of seconds..
        /// </summary>
        internal static string dlgDiapoExport_LabelFrequencyHundredth {
            get {
                return ResourceManager.GetString("dlgDiapoExport_LabelFrequencyHundredth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration of each Key Image : {0:0.00} seconds..
        /// </summary>
        internal static string dlgDiapoExport_LabelFrequencySeconds {
            get {
                return ResourceManager.GetString("dlgDiapoExport_LabelFrequencySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Original video with a pause on each Key Image.
        /// </summary>
        internal static string dlgDiapoExport_RadioPausedVideo {
            get {
                return ResourceManager.GetString("dlgDiapoExport_RadioPausedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Video slideshow with only the Key Images..
        /// </summary>
        internal static string dlgDiapoExport_RadioSlideshow {
            get {
                return ResourceManager.GetString("dlgDiapoExport_RadioSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Video.
        /// </summary>
        internal static string dlgDiapoExport_Title {
            get {
                return ResourceManager.GetString("dlgDiapoExport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OpenOffice Calc (*.ods)|*.ods|Microsoft Excel (*.xml)|*.xml|XHTML (*.html)|*.html|Text (*.txt)|*.txt;.
        /// </summary>
        internal static string dlgExportSpreadsheet_Filter {
            get {
                return ResourceManager.GetString("dlgExportSpreadsheet_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Data as a Spreadsheet Document.
        /// </summary>
        internal static string dlgExportSpreadsheet_Title {
            get {
                return ResourceManager.GetString("dlgExportSpreadsheet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PDF document (*.pdf)|*.pdf;.
        /// </summary>
        internal static string dlgExportToPDF_Filter {
            get {
                return ResourceManager.GetString("dlgExportToPDF_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save a PDF Document from Key Images.
        /// </summary>
        internal static string dlgExportToPDF_Title {
            get {
                return ResourceManager.GetString("dlgExportToPDF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comments....
        /// </summary>
        internal static string dlgKeyframeComment_Title {
            get {
                return ResourceManager.GetString("dlgKeyframeComment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinovea Video Analysis (*.kva)|*.kva|XML (*.xml)|*.xml|All Files (*.*)|*.*;.
        /// </summary>
        internal static string dlgLoadAnalysis_Filter {
            get {
                return ResourceManager.GetString("dlgLoadAnalysis_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load Key Images Data.
        /// </summary>
        internal static string dlgLoadAnalysis_Title {
            get {
                return ResourceManager.GetString("dlgLoadAnalysis_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations.
        /// </summary>
        internal static string dlgRafaleExport_GroupInfos {
            get {
                return ResourceManager.GetString("dlgRafaleExport_GroupInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blend drawings onto images..
        /// </summary>
        internal static string dlgRafaleExport_LabelBlend {
            get {
                return ResourceManager.GetString("dlgRafaleExport_LabelBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à one frame every {0} hundredth of seconds..
        /// </summary>
        internal static string dlgRafaleExport_LabelFrequencyHundredth {
            get {
                return ResourceManager.GetString("dlgRafaleExport_LabelFrequencyHundredth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frequency of image export :.
        /// </summary>
        internal static string dlgRafaleExport_LabelFrequencyRoot {
            get {
                return ResourceManager.GetString("dlgRafaleExport_LabelFrequencyRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à one frame every {0:0.00} seconds..
        /// </summary>
        internal static string dlgRafaleExport_LabelFrequencySeconds {
            get {
                return ResourceManager.GetString("dlgRafaleExport_LabelFrequencySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The suffix will be automatically appended to image file names. ( &quot;file&quot; =&gt; &quot;file-00.00.jpg&quot;).
        /// </summary>
        internal static string dlgRafaleExport_LabelInfoSuffix {
            get {
                return ResourceManager.GetString("dlgRafaleExport_LabelInfoSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Key Images only..
        /// </summary>
        internal static string dlgRafaleExport_LabelKeyframesOnly {
            get {
                return ResourceManager.GetString("dlgRafaleExport_LabelKeyframesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total images to export : {0:0} images..
        /// </summary>
        internal static string dlgRafaleExport_LabelTotalFrames {
            get {
                return ResourceManager.GetString("dlgRafaleExport_LabelTotalFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration covered by the exported sequence of images : {0:0.00} seconds..
        /// </summary>
        internal static string dlgRafaleExport_LabelTotalSeconds {
            get {
                return ResourceManager.GetString("dlgRafaleExport_LabelTotalSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save a Sequence of Images.
        /// </summary>
        internal static string dlgRafaleExport_Title {
            get {
                return ResourceManager.GetString("dlgRafaleExport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinovea Video Analysis (*.kva)|*.kva|XML (*.xml)|*.xml;.
        /// </summary>
        internal static string dlgSaveAnalysisFilter {
            get {
                return ResourceManager.GetString("dlgSaveAnalysisFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Take Slow Motion into account. (Current = .
        /// </summary>
        internal static string dlgSaveAnalysisOrVideo_CheckSlow {
            get {
                return ResourceManager.GetString("dlgSaveAnalysisOrVideo_CheckSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string dlgSaveAnalysisOrVideo_GroupOptions {
            get {
                return ResourceManager.GetString("dlgSaveAnalysisOrVideo_GroupOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Method.
        /// </summary>
        internal static string dlgSaveAnalysisOrVideo_GroupSaveMethod {
            get {
                return ResourceManager.GetString("dlgSaveAnalysisOrVideo_GroupSaveMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save only the key images data..
        /// </summary>
        internal static string dlgSaveAnalysisOrVideo_RadioAnalysis {
            get {
                return ResourceManager.GetString("dlgSaveAnalysisOrVideo_RadioAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Permanently paint key images data on the video..
        /// </summary>
        internal static string dlgSaveAnalysisOrVideo_RadioBlended {
            get {
                return ResourceManager.GetString("dlgSaveAnalysisOrVideo_RadioBlended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Combine video and key images data in the file..
        /// </summary>
        internal static string dlgSaveAnalysisOrVideo_RadioMuxed {
            get {
                return ResourceManager.GetString("dlgSaveAnalysisOrVideo_RadioMuxed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save video only..
        /// </summary>
        internal static string dlgSaveAnalysisOrVideo_RadioVideo {
            get {
                return ResourceManager.GetString("dlgSaveAnalysisOrVideo_RadioVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Video or Key Images Data....
        /// </summary>
        internal static string dlgSaveAnalysisOrVideo_Title {
            get {
                return ResourceManager.GetString("dlgSaveAnalysisOrVideo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Key Images Data.
        /// </summary>
        internal static string dlgSaveAnalysisTitle {
            get {
                return ResourceManager.GetString("dlgSaveAnalysisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All files (*.*)|*.*.
        /// </summary>
        internal static string dlgSaveFileFilter {
            get {
                return ResourceManager.GetString("dlgSaveFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JPEG Images (*.jpg,*.jpeg)|*.jpg;*.jpeg|PNG Images (*.png)|*.png|Bitmap Images (*.bmp)|*.bmp.
        /// </summary>
        internal static string dlgSaveFilter {
            get {
                return ResourceManager.GetString("dlgSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Sequence.
        /// </summary>
        internal static string dlgSaveSequenceTitle {
            get {
                return ResourceManager.GetString("dlgSaveSequenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Image .
        /// </summary>
        internal static string dlgSaveTitle {
            get {
                return ResourceManager.GetString("dlgSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matroska (*.mkv)|*.mkv|MP4 (*.mp4)|*.mp4|AVI (*.avi)|*.avi; .
        /// </summary>
        internal static string dlgSaveVideoFilterAlone {
            get {
                return ResourceManager.GetString("dlgSaveVideoFilterAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matroska (*.mkv)|*.mkv; .
        /// </summary>
        internal static string dlgSaveVideoFilterMuxed {
            get {
                return ResourceManager.GetString("dlgSaveVideoFilterMuxed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Video.
        /// </summary>
        internal static string dlgSaveVideoTitle {
            get {
                return ResourceManager.GetString("dlgSaveVideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply to all paths..
        /// </summary>
        internal static string dlgSetTrajectoryOrigin_ApplyToAll {
            get {
                return ResourceManager.GetString("dlgSetTrajectoryOrigin_ApplyToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set coordinates system origin.
        /// </summary>
        internal static string dlgSetTrajectoryOrigin_Title {
            get {
                return ResourceManager.GetString("dlgSetTrajectoryOrigin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinovea - Cannot create Slideshow..
        /// </summary>
        internal static string Error_SaveDiaporama {
            get {
                return ResourceManager.GetString("Error_SaveDiaporama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A Slideshow is a sequence of Key Images saved in video format.\n Please add some Key Images before generating the Slideshow..
        /// </summary>
        internal static string Error_SaveDiaporama_NoKeyframes {
            get {
                return ResourceManager.GetString("Error_SaveDiaporama_NoKeyframes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to write file.\nMake sure you have the rights to write in the target folder and that the file is not currently used..
        /// </summary>
        internal static string Error_SaveMovie_FileError {
            get {
                return ResourceManager.GetString("Error_SaveMovie_FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to save video.\nTry again with a different format..
        /// </summary>
        internal static string Error_SaveMovie_LowLevelError {
            get {
                return ResourceManager.GetString("Error_SaveMovie_LowLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinovea - Unable to Save Video. .
        /// </summary>
        internal static string Error_SaveMovie_Title {
            get {
                return ResourceManager.GetString("Error_SaveMovie_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinovea – Cannot create paused video.
        /// </summary>
        internal static string Error_SavePausedVideo {
            get {
                return ResourceManager.GetString("Error_SavePausedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to add some key images before using this function..
        /// </summary>
        internal static string Error_SavePausedVideo_NoKeyframes {
            get {
                return ResourceManager.GetString("Error_SavePausedVideo_NoKeyframes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinovea - Cannot Create Pdf Document. .
        /// </summary>
        internal static string Error_SavePdf {
            get {
                return ResourceManager.GetString("Error_SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to save file : the file is open in another window..
        /// </summary>
        internal static string Error_SavePdf_IOException {
            get {
                return ResourceManager.GetString("Error_SavePdf_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Pdf document will be created out of Key Images.\n Please add some Key Images before generating the document. .
        /// </summary>
        internal static string Error_SavePdf_NoKeyFrames {
            get {
                return ResourceManager.GetString("Error_SavePdf_NoKeyFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progress :.
        /// </summary>
        internal static string FormFileSave_Infos {
            get {
                return ResourceManager.GetString("FormFileSave_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving Video....
        /// </summary>
        internal static string FormFileSave_Title {
            get {
                return ResourceManager.GetString("FormFileSave_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exported Images :.
        /// </summary>
        internal static string FormFramesExport_Infos {
            get {
                return ResourceManager.GetString("FormFramesExport_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exporting Images....
        /// </summary>
        internal static string FormFramesExport_Title {
            get {
                return ResourceManager.GetString("FormFramesExport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decompressed Frames : .
        /// </summary>
        internal static string FormFramesImport_Infos {
            get {
                return ResourceManager.GetString("FormFramesImport_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Importing Frames....
        /// </summary>
        internal static string FormFramesImport_Title {
            get {
                return ResourceManager.GetString("FormFramesImport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progress.
        /// </summary>
        internal static string FormProgressBar_Title {
            get {
                return ResourceManager.GetString("FormProgressBar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appearance.
        /// </summary>
        internal static string Generic_Appearance {
            get {
                return ResourceManager.GetString("Generic_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply.
        /// </summary>
        internal static string Generic_Apply {
            get {
                return ResourceManager.GetString("Generic_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string Generic_Close {
            get {
                return ResourceManager.GetString("Generic_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color :.
        /// </summary>
        internal static string Generic_ColorPicker {
            get {
                return ResourceManager.GetString("Generic_ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        internal static string Generic_Configuration {
            get {
                return ResourceManager.GetString("Generic_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Font Size :.
        /// </summary>
        internal static string Generic_FontSizePicker {
            get {
                return ResourceManager.GetString("Generic_FontSizePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image.
        /// </summary>
        internal static string Generic_Image {
            get {
                return ResourceManager.GetString("Generic_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string Generic_Save {
            get {
                return ResourceManager.GetString("Generic_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key images have been modified.\nDo you want to save key images data before closing ?.
        /// </summary>
        internal static string InfoBox_MetadataIsDirty_Text {
            get {
                return ResourceManager.GetString("InfoBox_MetadataIsDirty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key images data not saved.
        /// </summary>
        internal static string InfoBox_MetadataIsDirty_Title {
            get {
                return ResourceManager.GetString("InfoBox_MetadataIsDirty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Common Controls :.
        /// </summary>
        internal static string lblInfo_Text {
            get {
                return ResourceManager.GetString("lblInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration.
        /// </summary>
        internal static string lblSelDuration_Text {
            get {
                return ResourceManager.GetString("lblSelDuration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        internal static string lblSelStartSelection_Text {
            get {
                return ResourceManager.GetString("lblSelStartSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speed :.
        /// </summary>
        internal static string lblSpeedTuner_Text {
            get {
                return ResourceManager.GetString("lblSpeedTuner_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position.
        /// </summary>
        internal static string lblTimeCode_Text {
            get {
                return ResourceManager.GetString("lblTimeCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Working Zone:.
        /// </summary>
        internal static string lblWorkingZone_Text {
            get {
                return ResourceManager.GetString("lblWorkingZone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centimeters.
        /// </summary>
        internal static string LengthUnit_Centimeters {
            get {
                return ResourceManager.GetString("LengthUnit_Centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feet.
        /// </summary>
        internal static string LengthUnit_Feet {
            get {
                return ResourceManager.GetString("LengthUnit_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inches.
        /// </summary>
        internal static string LengthUnit_Inches {
            get {
                return ResourceManager.GetString("LengthUnit_Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Meters.
        /// </summary>
        internal static string LengthUnit_Meters {
            get {
                return ResourceManager.GetString("LengthUnit_Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yards.
        /// </summary>
        internal static string LengthUnit_Yards {
            get {
                return ResourceManager.GetString("LengthUnit_Yards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to open the file : unsupported video stream..
        /// </summary>
        internal static string LoadMovie_CodecNotFound {
            get {
                return ResourceManager.GetString("LoadMovie_CodecNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to open the file : problem while initializing decoder..
        /// </summary>
        internal static string LoadMovie_CodecNotOpened {
            get {
                return ResourceManager.GetString("LoadMovie_CodecNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to open the file : file type is not supported..
        /// </summary>
        internal static string LoadMovie_CodecNotSupported {
            get {
                return ResourceManager.GetString("LoadMovie_CodecNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinovea - Loading Error..
        /// </summary>
        internal static string LoadMovie_Error {
            get {
                return ResourceManager.GetString("LoadMovie_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to open the file : file not found or empty..
        /// </summary>
        internal static string LoadMovie_FileNotOpened {
            get {
                return ResourceManager.GetString("LoadMovie_FileNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to open the file : Image format is not supported..
        /// </summary>
        internal static string LoadMovie_ImageFormatError {
            get {
                return ResourceManager.GetString("LoadMovie_ImageFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to open the file : inconsistencies found. Please check encoding process..
        /// </summary>
        internal static string LoadMovie_InconsistantMovieError {
            get {
                return ResourceManager.GetString("LoadMovie_InconsistantMovieError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to open the file : stream information not found..
        /// </summary>
        internal static string LoadMovie_StreamInfoNotFound {
            get {
                return ResourceManager.GetString("LoadMovie_StreamInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to open the file : unknown error..
        /// </summary>
        internal static string LoadMovie_UnkownError {
            get {
                return ResourceManager.GetString("LoadMovie_UnkownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to open the file : video stream not found..
        /// </summary>
        internal static string LoadMovie_VideoStreamNotFound {
            get {
                return ResourceManager.GetString("LoadMovie_VideoStreamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Canceling....
        /// </summary>
        internal static string LoadMovieProgress_Cancellation {
            get {
                return ResourceManager.GetString("LoadMovieProgress_Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decoded frames :.
        /// </summary>
        internal static string LoadMovieProgress_Infos {
            get {
                return ResourceManager.GetString("LoadMovieProgress_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File Load Progress.
        /// </summary>
        internal static string LoadMovieProgress_Title {
            get {
                return ResourceManager.GetString("LoadMovieProgress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total unknown.
        /// </summary>
        internal static string LoadMovieProgress_TotalUnknown {
            get {
                return ResourceManager.GetString("LoadMovieProgress_TotalUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lock the Working Zone Boundaries.
        /// </summary>
        internal static string LockSelectionLock {
            get {
                return ResourceManager.GetString("LockSelectionLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unlock the Working Zone Boundaries.
        /// </summary>
        internal static string LockSelectionUnlock {
            get {
                return ResourceManager.GetString("LockSelectionUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Perspective Grid.
        /// </summary>
        internal static string mnu3DPlane {
            get {
                return ResourceManager.GetString("mnu3DPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brightness....
        /// </summary>
        internal static string mnuBrightness {
            get {
                return ResourceManager.GetString("mnuBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure.
        /// </summary>
        internal static string mnuChronoConfigure {
            get {
                return ResourceManager.GetString("mnuChronoConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Countdown Mode.
        /// </summary>
        internal static string mnuChronoCountdown {
            get {
                return ResourceManager.GetString("mnuChronoCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Stopwatch.
        /// </summary>
        internal static string mnuChronoDelete {
            get {
                return ResourceManager.GetString("mnuChronoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hide Stopwatch.
        /// </summary>
        internal static string mnuChronoHide {
            get {
                return ResourceManager.GetString("mnuChronoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Stopwatch.
        /// </summary>
        internal static string mnuChronoStart {
            get {
                return ResourceManager.GetString("mnuChronoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop Stopwatch.
        /// </summary>
        internal static string mnuChronoStop {
            get {
                return ResourceManager.GetString("mnuChronoStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close This Screen.
        /// </summary>
        internal static string mnuCloseScreen {
            get {
                return ResourceManager.GetString("mnuCloseScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Colors....
        /// </summary>
        internal static string mnuColors {
            get {
                return ResourceManager.GetString("mnuColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color.
        /// </summary>
        internal static string mnuConfigureDrawing_Color {
            get {
                return ResourceManager.GetString("mnuConfigureDrawing_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color and Size....
        /// </summary>
        internal static string mnuConfigureDrawing_ColorSize {
            get {
                return ResourceManager.GetString("mnuConfigureDrawing_ColorSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Persistence....
        /// </summary>
        internal static string mnuConfigureFading {
            get {
                return ResourceManager.GetString("mnuConfigureFading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure Path Display.
        /// </summary>
        internal static string mnuConfigureTrajectory {
            get {
                return ResourceManager.GetString("mnuConfigureTrajectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deinterlace.
        /// </summary>
        internal static string mnuDeinterlace {
            get {
                return ResourceManager.GetString("mnuDeinterlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string mnuDeleteDrawing {
            get {
                return ResourceManager.GetString("mnuDeleteDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Path after this Point.
        /// </summary>
        internal static string mnuDeleteEndOfTrajectory {
            get {
                return ResourceManager.GetString("mnuDeleteEndOfTrajectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete all the Path.
        /// </summary>
        internal static string mnuDeleteTrajectory {
            get {
                return ResourceManager.GetString("mnuDeleteTrajectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edges Only....
        /// </summary>
        internal static string mnuEdges {
            get {
                return ResourceManager.GetString("mnuEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Microsoft Excel (MS-XML).
        /// </summary>
        internal static string mnuExportMSXML {
            get {
                return ResourceManager.GetString("mnuExportMSXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OpenOffice Calc (ODF).
        /// </summary>
        internal static string mnuExportODF {
            get {
                return ResourceManager.GetString("mnuExportODF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to Spreadsheet.
        /// </summary>
        internal static string mnuExportSpreadsheet {
            get {
                return ResourceManager.GetString("mnuExportSpreadsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trajectories to simple text.
        /// </summary>
        internal static string mnuExportTEXT {
            get {
                return ResourceManager.GetString("mnuExportTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to PDF.
        /// </summary>
        internal static string mnuExportToPDF {
            get {
                return ResourceManager.GetString("mnuExportToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XHTML.
        /// </summary>
        internal static string mnuExportXHTML {
            get {
                return ResourceManager.GetString("mnuExportXHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fluidify.
        /// </summary>
        internal static string mnuFluidify {
            get {
                return ResourceManager.GetString("mnuFluidify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image Format.
        /// </summary>
        internal static string mnuFormat {
            get {
                return ResourceManager.GetString("mnuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto Detection.
        /// </summary>
        internal static string mnuFormatAuto {
            get {
                return ResourceManager.GetString("mnuFormatAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Force 16:9.
        /// </summary>
        internal static string mnuFormatForce169 {
            get {
                return ResourceManager.GetString("mnuFormatForce169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Force 4:3.
        /// </summary>
        internal static string mnuFormatForce43 {
            get {
                return ResourceManager.GetString("mnuFormatForce43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Key Image.
        /// </summary>
        internal static string mnuGotoKeyframe {
            get {
                return ResourceManager.GetString("mnuGotoKeyframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grid.
        /// </summary>
        internal static string mnuGrid {
            get {
                return ResourceManager.GetString("mnuGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hide.
        /// </summary>
        internal static string mnuGridsHide {
            get {
                return ResourceManager.GetString("mnuGridsHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load Key Images Data....
        /// </summary>
        internal static string mnuLoadAnalysis {
            get {
                return ResourceManager.GetString("mnuLoadAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom x1.5.
        /// </summary>
        internal static string mnuMagnifier150 {
            get {
                return ResourceManager.GetString("mnuMagnifier150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom x1.75.
        /// </summary>
        internal static string mnuMagnifier175 {
            get {
                return ResourceManager.GetString("mnuMagnifier175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom x2.
        /// </summary>
        internal static string mnuMagnifier200 {
            get {
                return ResourceManager.GetString("mnuMagnifier200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom x2.25.
        /// </summary>
        internal static string mnuMagnifier225 {
            get {
                return ResourceManager.GetString("mnuMagnifier225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom x2.5.
        /// </summary>
        internal static string mnuMagnifier250 {
            get {
                return ResourceManager.GetString("mnuMagnifier250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Switch to Direct Zoom.
        /// </summary>
        internal static string mnuMagnifierDirect {
            get {
                return ResourceManager.GetString("mnuMagnifierDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close Magnifier.
        /// </summary>
        internal static string mnuMagnifierQuit {
            get {
                return ResourceManager.GetString("mnuMagnifierQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mirror.
        /// </summary>
        internal static string mnuMirror {
            get {
                return ResourceManager.GetString("mnuMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One Capture Screen.
        /// </summary>
        internal static string mnuOneCapture {
            get {
                return ResourceManager.GetString("mnuOneCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One Playback Screen.
        /// </summary>
        internal static string mnuOnePlayer {
            get {
                return ResourceManager.GetString("mnuOnePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play | Pause.
        /// </summary>
        internal static string mnuPlayPause {
            get {
                return ResourceManager.GetString("mnuPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart Path Edition.
        /// </summary>
        internal static string mnuRestartTracking {
            get {
                return ResourceManager.GetString("mnuRestartTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save....
        /// </summary>
        internal static string mnuSave {
            get {
                return ResourceManager.GetString("mnuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save the Current Image to File.
        /// </summary>
        internal static string mnuSavePic {
            get {
                return ResourceManager.GetString("mnuSavePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Screens.
        /// </summary>
        internal static string mnuScreens {
            get {
                return ResourceManager.GetString("mnuScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calibrate measure....
        /// </summary>
        internal static string mnuSealMeasure {
            get {
                return ResourceManager.GetString("mnuSealMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à High-speed camera....
        /// </summary>
        internal static string mnuSetCaptureSpeed {
            get {
                return ResourceManager.GetString("mnuSetCaptureSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the Last Frame of Working Zone to the Current Frame.
        /// </summary>
        internal static string mnuSetSelectionEnd {
            get {
                return ResourceManager.GetString("mnuSetSelectionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the First Frame of Working Zone to the Current Frame.
        /// </summary>
        internal static string mnuSetSelectionStart {
            get {
                return ResourceManager.GetString("mnuSetSelectionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sharpen....
        /// </summary>
        internal static string mnuSharpen {
            get {
                return ResourceManager.GetString("mnuSharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display Measure.
        /// </summary>
        internal static string mnuShowMeasure {
            get {
                return ResourceManager.GetString("mnuShowMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stabilize.
        /// </summary>
        internal static string mnuStabilize {
            get {
                return ResourceManager.GetString("mnuStabilize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End Path Edition .
        /// </summary>
        internal static string mnuStopTracking {
            get {
                return ResourceManager.GetString("mnuStopTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Observational reference.
        /// </summary>
        internal static string mnuSVGTools {
            get {
                return ResourceManager.GetString("mnuSVGTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invert Videos Positions.
        /// </summary>
        internal static string mnuSwapScreens {
            get {
                return ResourceManager.GetString("mnuSwapScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete file.
        /// </summary>
        internal static string mnuThumbnailDelete {
            get {
                return ResourceManager.GetString("mnuThumbnailDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play video.
        /// </summary>
        internal static string mnuThumbnailPlay {
            get {
                return ResourceManager.GetString("mnuThumbnailPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename file.
        /// </summary>
        internal static string mnuThumbnailRename {
            get {
                return ResourceManager.GetString("mnuThumbnailRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show/Hide Common Controls.
        /// </summary>
        internal static string mnuToggleCommonCtrls {
            get {
                return ResourceManager.GetString("mnuToggleCommonCtrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Track Path.
        /// </summary>
        internal static string mnuTrackTrajectory {
            get {
                return ResourceManager.GetString("mnuTrackTrajectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two Capture Screens.
        /// </summary>
        internal static string mnuTwoCaptures {
            get {
                return ResourceManager.GetString("mnuTwoCaptures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One Capture screen and one Playback screen.
        /// </summary>
        internal static string mnuTwoMixed {
            get {
                return ResourceManager.GetString("mnuTwoMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two Playback Screens.
        /// </summary>
        internal static string mnuTwoPlayers {
            get {
                return ResourceManager.GetString("mnuTwoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An Unknown Error Occurred..
        /// </summary>
        internal static string PlayMovie_AccessViolation {
            get {
                return ResourceManager.GetString("PlayMovie_AccessViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinovea - Playing Error..
        /// </summary>
        internal static string PlayMovie_Error {
            get {
                return ResourceManager.GetString("PlayMovie_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to save file : unsupported encoding..
        /// </summary>
        internal static string SaveMovie_CodecNotFound {
            get {
                return ResourceManager.GetString("SaveMovie_CodecNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to save file : problem while initializing encoder..
        /// </summary>
        internal static string SaveMovie_CodecNotOpened {
            get {
                return ResourceManager.GetString("SaveMovie_CodecNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinovea - Saving error..
        /// </summary>
        internal static string SaveMovie_Error {
            get {
                return ResourceManager.GetString("SaveMovie_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to save file : Unable to write to the file..
        /// </summary>
        internal static string SaveMovie_FileNotOpened {
            get {
                return ResourceManager.GetString("SaveMovie_FileNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to save file : some error happened during encoding process..
        /// </summary>
        internal static string SaveMovie_TranscodeNotFinished {
            get {
                return ResourceManager.GetString("SaveMovie_TranscodeNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failure: Unable to save file : unknown error..
        /// </summary>
        internal static string SaveMovie_UnknownError {
            get {
                return ResourceManager.GetString("SaveMovie_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty.
        /// </summary>
        internal static string statusEmptyScreen {
            get {
                return ResourceManager.GetString("statusEmptyScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classic (h:mm:ss:hundredth).
        /// </summary>
        internal static string TimeCodeFormat_Classic {
            get {
                return ResourceManager.GetString("TimeCodeFormat_Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frames Numbers.
        /// </summary>
        internal static string TimeCodeFormat_Frames {
            get {
                return ResourceManager.GetString("TimeCodeFormat_Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hundredth of a minute.
        /// </summary>
        internal static string TimeCodeFormat_HundredthOfMinutes {
            get {
                return ResourceManager.GetString("TimeCodeFormat_HundredthOfMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ten thousandth of an hour.
        /// </summary>
        internal static string TimeCodeFormat_TenThousandthOfHours {
            get {
                return ResourceManager.GetString("TimeCodeFormat_TenThousandthOfHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This Video is the Active Video.
        /// </summary>
        internal static string ToolTip_ActiveScreenIndicator {
            get {
                return ResourceManager.GetString("ToolTip_ActiveScreenIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a Key Image.
        /// </summary>
        internal static string ToolTip_AddKeyframe {
            get {
                return ResourceManager.GetString("ToolTip_AddKeyframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Switch Back to Normal Mode .
        /// </summary>
        internal static string ToolTip_AnalyseModeAnalyse {
            get {
                return ResourceManager.GetString("ToolTip_AnalyseModeAnalyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Switch to Analysis Mode.
        /// </summary>
        internal static string ToolTip_AnalyseModeNormal {
            get {
                return ResourceManager.GetString("ToolTip_AnalyseModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Previous Frame.
        /// </summary>
        internal static string ToolTip_Back {
            get {
                return ResourceManager.GetString("ToolTip_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color Profile.
        /// </summary>
        internal static string ToolTip_ColorProfile {
            get {
                return ResourceManager.GetString("ToolTip_ColorProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable superposition of images.
        /// </summary>
        internal static string ToolTip_CommonCtrl_DisableMerge {
            get {
                return ResourceManager.GetString("ToolTip_CommonCtrl_DisableMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable superposition of images.
        /// </summary>
        internal static string ToolTip_CommonCtrl_EnableMerge {
            get {
                return ResourceManager.GetString("ToolTip_CommonCtrl_EnableMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy Previous Key Image Drawings into the Current Image.
        /// </summary>
        internal static string ToolTip_CopyDrawings {
            get {
                return ResourceManager.GetString("ToolTip_CopyDrawings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Angle.
        /// </summary>
        internal static string ToolTip_DrawingToolAngle2D {
            get {
                return ResourceManager.GetString("ToolTip_DrawingToolAngle2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stopwatch.
        /// </summary>
        internal static string ToolTip_DrawingToolChrono {
            get {
                return ResourceManager.GetString("ToolTip_DrawingToolChrono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cross Marker.
        /// </summary>
        internal static string ToolTip_DrawingToolCross2D {
            get {
                return ResourceManager.GetString("ToolTip_DrawingToolCross2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Line.
        /// </summary>
        internal static string ToolTip_DrawingToolLine2D {
            get {
                return ResourceManager.GetString("ToolTip_DrawingToolLine2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pencil.
        /// </summary>
        internal static string ToolTip_DrawingToolPencil {
            get {
                return ResourceManager.GetString("ToolTip_DrawingToolPencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move.
        /// </summary>
        internal static string ToolTip_DrawingToolPointer {
            get {
                return ResourceManager.GetString("ToolTip_DrawingToolPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text.
        /// </summary>
        internal static string ToolTip_DrawingToolText {
            get {
                return ResourceManager.GetString("ToolTip_DrawingToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go Back to Beginning.
        /// </summary>
        internal static string ToolTip_First {
            get {
                return ResourceManager.GetString("ToolTip_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jump to End.
        /// </summary>
        internal static string ToolTip_Last {
            get {
                return ResourceManager.GetString("ToolTip_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magnifier.
        /// </summary>
        internal static string ToolTip_Magnifier {
            get {
                return ResourceManager.GetString("ToolTip_Magnifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Next Frame.
        /// </summary>
        internal static string ToolTip_Next {
            get {
                return ResourceManager.GetString("ToolTip_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play | Pause.
        /// </summary>
        internal static string ToolTip_Play {
            get {
                return ResourceManager.GetString("ToolTip_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Repeat Mode ( Once | Loop ) - Current Mode : Loop.
        /// </summary>
        internal static string ToolTip_PlayingMode_Loop {
            get {
                return ResourceManager.GetString("ToolTip_PlayingMode_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Repeat Mode ( Once | Loop ) - Current Mode : Once.
        /// </summary>
        internal static string ToolTip_PlayingMode_Once {
            get {
                return ResourceManager.GetString("ToolTip_PlayingMode_Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save a Sequence of Images.
        /// </summary>
        internal static string ToolTip_Rafale {
            get {
                return ResourceManager.GetString("ToolTip_Rafale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset the Working Zone to Full Video.
        /// </summary>
        internal static string ToolTip_ResetWorkingZone {
            get {
                return ResourceManager.GetString("ToolTip_ResetWorkingZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save a slideshow from Key Images.
        /// </summary>
        internal static string ToolTip_SaveDiaporama {
            get {
                return ResourceManager.GetString("ToolTip_SaveDiaporama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save video with a pause on each key image.
        /// </summary>
        internal static string ToolTip_SavePausedVideo {
            get {
                return ResourceManager.GetString("ToolTip_SavePausedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the First Frame of Working Zone to the Current Frame.
        /// </summary>
        internal static string ToolTip_SetHandlerLeft {
            get {
                return ResourceManager.GetString("ToolTip_SetHandlerLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the Last Frame of Working Zone to the Current Frame.
        /// </summary>
        internal static string ToolTip_SetHandlerRight {
            get {
                return ResourceManager.GetString("ToolTip_SetHandlerRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Comments.
        /// </summary>
        internal static string ToolTip_ShowComments {
            get {
                return ResourceManager.GetString("ToolTip_ShowComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vary Playback Speed.
        /// </summary>
        internal static string ToolTip_sldrSpeed {
            get {
                return ResourceManager.GetString("ToolTip_sldrSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save the Current Image to File.
        /// </summary>
        internal static string ToolTip_Snapshot {
            get {
                return ResourceManager.GetString("ToolTip_Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the Working Zone.
        /// </summary>
        internal static string ToolTip_trkSelection {
            get {
                return ResourceManager.GetString("ToolTip_trkSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto Levels....
        /// </summary>
        internal static string VideoFilterAutoLevels_FriendlyName {
            get {
                return ResourceManager.GetString("VideoFilterAutoLevels_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto Contrast....
        /// </summary>
        internal static string VideoFilterContrast_FriendlyName {
            get {
                return ResourceManager.GetString("VideoFilterContrast_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edges Only....
        /// </summary>
        internal static string VideoFilterEdgesOnly_FriendlyName {
            get {
                return ResourceManager.GetString("VideoFilterEdgesOnly_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Overview....
        /// </summary>
        internal static string VideoFilterMosaic_FriendlyName {
            get {
                return ResourceManager.GetString("VideoFilterMosaic_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reverse....
        /// </summary>
        internal static string VideoFilterReverse_FriendlyName {
            get {
                return ResourceManager.GetString("VideoFilterReverse_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sharpen....
        /// </summary>
        internal static string VideoFilterSharpen_FriendlyName {
            get {
                return ResourceManager.GetString("VideoFilterSharpen_FriendlyName", resourceCulture);
            }
        }
    }
}
