//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3053
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinovea.Root.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RootLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RootLang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kinovea.Root.Languages.RootLang", typeof(RootLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Language.
        /// </summary>
        internal static string CommandSwitchUICulture_FriendlyName {
            get {
                return ResourceManager.GetString("CommandSwitchUICulture_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show/Hide File Explorer.
        /// </summary>
        internal static string CommandToggleFileExplorer_FriendlyName {
            get {
                return ResourceManager.GetString("CommandToggleFileExplorer_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n Kinovea is subject to the terms of the Gnu General Public License version 2.\n.
        /// </summary>
        internal static string dlgAbout_Info1 {
            get {
                return ResourceManager.GetString("dlgAbout_Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n Kinovea works in co-operation with the following software components:\n\n.
        /// </summary>
        internal static string dlgAbout_Info2 {
            get {
                return ResourceManager.GetString("dlgAbout_Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n You are welcome to help translate, test, debug, improve or otherwise support Kinovea.\n.
        /// </summary>
        internal static string dlgAbout_Info3 {
            get {
                return ResourceManager.GetString("dlgAbout_Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \n Localisations:\n.
        /// </summary>
        internal static string dlgAbout_Info4 {
            get {
                return ResourceManager.GetString("dlgAbout_Info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All Languages.
        /// </summary>
        internal static string dlgHelpVideos_FilterAll {
            get {
                return ResourceManager.GetString("dlgHelpVideos_FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à More videos are available through the menu : Options &gt; Check For Available Updates....
        /// </summary>
        internal static string dlgHelpVideos_GetMore {
            get {
                return ResourceManager.GetString("dlgHelpVideos_GetMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About this Video….
        /// </summary>
        internal static string dlgHelpVideos_LblAboutThisVideo {
            get {
                return ResourceManager.GetString("dlgHelpVideos_LblAboutThisVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter by language :.
        /// </summary>
        internal static string dlgHelpVideos_LblFilterByLang {
            get {
                return ResourceManager.GetString("dlgHelpVideos_LblFilterByLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select which video you would like to view:.
        /// </summary>
        internal static string dlgHelpVideos_LblSelectVideos {
            get {
                return ResourceManager.GetString("dlgHelpVideos_LblSelectVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Comment..
        /// </summary>
        internal static string dlgHelpVideos_NoComment {
            get {
                return ResourceManager.GetString("dlgHelpVideos_NoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinovea - Watch a Video Tutorial..
        /// </summary>
        internal static string dlgHelpVideos_Title {
            get {
                return ResourceManager.GetString("dlgHelpVideos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Watch.
        /// </summary>
        internal static string dlgHelpVideos_Watch {
            get {
                return ResourceManager.GetString("dlgHelpVideos_Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All files (*.*)|*.*.
        /// </summary>
        internal static string dlgOpenFile_Filter {
            get {
                return ResourceManager.GetString("dlgOpenFile_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Video File.
        /// </summary>
        internal static string dlgOpenFile_Title {
            get {
                return ResourceManager.GetString("dlgOpenFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drawings.
        /// </summary>
        internal static string dlgPreferences_btnDrawings {
            get {
                return ResourceManager.GetString("dlgPreferences_btnDrawings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General.
        /// </summary>
        internal static string dlgPreferences_ButtonGeneral {
            get {
                return ResourceManager.GetString("dlgPreferences_ButtonGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play / Analyze.
        /// </summary>
        internal static string dlgPreferences_ButtonPlayAnalyze {
            get {
                return ResourceManager.GetString("dlgPreferences_ButtonPlayAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show drawings when video is playing.
        /// </summary>
        internal static string dlgPreferences_chkDrawOnPlay {
            get {
                return ResourceManager.GetString("dlgPreferences_chkDrawOnPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable persistence.
        /// </summary>
        internal static string dlgPreferences_chkEnablePersistence {
            get {
                return ResourceManager.GetString("dlgPreferences_chkEnablePersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Switch To Analysis Mode.
        /// </summary>
        internal static string dlgPreferences_GroupAnalysisMode {
            get {
                return ResourceManager.GetString("dlgPreferences_GroupAnalysisMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Colors.
        /// </summary>
        internal static string dlgPreferences_GroupColors {
            get {
                return ResourceManager.GetString("dlgPreferences_GroupColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Persistence.
        /// </summary>
        internal static string dlgPreferences_grpPersistence {
            get {
                return ResourceManager.GetString("dlgPreferences_grpPersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grid :.
        /// </summary>
        internal static string dlgPreferences_LabelGrid {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of files in history :.
        /// </summary>
        internal static string dlgPreferences_LabelHistoryCount {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelHistoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language :.
        /// </summary>
        internal static string dlgPreferences_LabelLanguages {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à And.
        /// </summary>
        internal static string dlgPreferences_LabelLogic {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Perspective Grid:.
        /// </summary>
        internal static string dlgPreferences_LabelPlane3D {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelPlane3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time markers format :.
        /// </summary>
        internal static string dlgPreferences_LabelTimeFormat {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Working Zone will take less than {0} MB of Memory..
        /// </summary>
        internal static string dlgPreferences_LabelWorkingZoneMemory {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelWorkingZoneMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Working Zone is less than {0} seconds..
        /// </summary>
        internal static string dlgPreferences_LabelWorkingZoneSeconds {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelWorkingZoneSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By default, drawings will stay visible for {0} images around the Key Image..
        /// </summary>
        internal static string dlgPreferences_lblFading {
            get {
                return ResourceManager.GetString("dlgPreferences_lblFading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preferences….
        /// </summary>
        internal static string dlgPreferences_Title {
            get {
                return ResourceManager.GetString("dlgPreferences_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading User Interface….
        /// </summary>
        internal static string dlgSplash_LoadInfos {
            get {
                return ResourceManager.GetString("dlgSplash_LoadInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        internal static string Generic_Quit {
            get {
                return ResourceManager.GetString("Generic_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string Generic_Save {
            get {
                return ResourceManager.GetString("Generic_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About Kinovea….
        /// </summary>
        internal static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open log folder….
        /// </summary>
        internal static string mnuApplicationFolder {
            get {
                return ResourceManager.GetString("mnuApplicationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        internal static string mnuEdit {
            get {
                return ResourceManager.GetString("mnuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        internal static string mnuFile {
            get {
                return ResourceManager.GetString("mnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        internal static string mnuHelp {
            get {
                return ResourceManager.GetString("mnuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinovea Help....
        /// </summary>
        internal static string mnuHelpContents {
            get {
                return ResourceManager.GetString("mnuHelpContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent.
        /// </summary>
        internal static string mnuHistory {
            get {
                return ResourceManager.GetString("mnuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset History.
        /// </summary>
        internal static string mnuHistoryReset {
            get {
                return ResourceManager.GetString("mnuHistoryReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image.
        /// </summary>
        internal static string mnuImage {
            get {
                return ResourceManager.GetString("mnuImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string mnuLanguages {
            get {
                return ResourceManager.GetString("mnuLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Motion.
        /// </summary>
        internal static string mnuMotion {
            get {
                return ResourceManager.GetString("mnuMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Video File….
        /// </summary>
        internal static string mnuOpenFile {
            get {
                return ResourceManager.GetString("mnuOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string mnuOptions {
            get {
                return ResourceManager.GetString("mnuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preferences….
        /// </summary>
        internal static string mnuPreferences {
            get {
                return ResourceManager.GetString("mnuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Redo.
        /// </summary>
        internal static string mnuRedo {
            get {
                return ResourceManager.GetString("mnuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View.
        /// </summary>
        internal static string mnuScreens {
            get {
                return ResourceManager.GetString("mnuScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File Explorer.
        /// </summary>
        internal static string mnuToggleFileExplorer {
            get {
                return ResourceManager.GetString("mnuToggleFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Video Tutorials….
        /// </summary>
        internal static string mnuTutorialVideos {
            get {
                return ResourceManager.GetString("mnuTutorialVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Undo.
        /// </summary>
        internal static string mnuUndo {
            get {
                return ResourceManager.GetString("mnuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classic (h:mm:ss:hundredth).
        /// </summary>
        internal static string TimeCodeFormat_Classic {
            get {
                return ResourceManager.GetString("TimeCodeFormat_Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frames Numbers.
        /// </summary>
        internal static string TimeCodeFormat_Frames {
            get {
                return ResourceManager.GetString("TimeCodeFormat_Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hundredth of a minute.
        /// </summary>
        internal static string TimeCodeFormat_HundredthOfMinutes {
            get {
                return ResourceManager.GetString("TimeCodeFormat_HundredthOfMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ten thousandth of an hour.
        /// </summary>
        internal static string TimeCodeFormat_TenThousandthOfHours {
            get {
                return ResourceManager.GetString("TimeCodeFormat_TenThousandthOfHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classic + Frame numbers.
        /// </summary>
        internal static string TimeCodeFormat_TimeAndFrames {
            get {
                return ResourceManager.GetString("TimeCodeFormat_TimeAndFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time Stamps.
        /// </summary>
        internal static string TimeCodeFormat_Timestamps {
            get {
                return ResourceManager.GetString("TimeCodeFormat_Timestamps", resourceCulture);
            }
        }
    }
}
