//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videa.Root.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RootLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RootLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Videa.Root.Languages.RootLang", typeof(RootLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string CommandSwitchUICulture_FriendlyName {
            get {
                return ResourceManager.GetString("CommandSwitchUICulture_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide File Explorer.
        /// </summary>
        internal static string CommandToggleFileExplorer_FriendlyName {
            get {
                return ResourceManager.GetString("CommandToggleFileExplorer_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n Kinovea is subject to the terms of the Gnu General Public License version 2.\n.
        /// </summary>
        internal static string dlgAbout_Info1 {
            get {
                return ResourceManager.GetString("dlgAbout_Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n Kinovea works in co-operation with the following software components:\n\n.
        /// </summary>
        internal static string dlgAbout_Info2 {
            get {
                return ResourceManager.GetString("dlgAbout_Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n You are welcome to help translate, test, debug, improve or otherwise support Kinovea.\n.
        /// </summary>
        internal static string dlgAbout_Info3 {
            get {
                return ResourceManager.GetString("dlgAbout_Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n Localisations:\n.
        /// </summary>
        internal static string dlgAbout_Info4 {
            get {
                return ResourceManager.GetString("dlgAbout_Info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Languages.
        /// </summary>
        internal static string dlgHelpVideos_FilterAll {
            get {
                return ResourceManager.GetString("dlgHelpVideos_FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can get more videos through the menu : Options &gt; Check For Available Updates....
        /// </summary>
        internal static string dlgHelpVideos_GetMore {
            get {
                return ResourceManager.GetString("dlgHelpVideos_GetMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this Video....
        /// </summary>
        internal static string dlgHelpVideos_LblAboutThisVideo {
            get {
                return ResourceManager.GetString("dlgHelpVideos_LblAboutThisVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by language :.
        /// </summary>
        internal static string dlgHelpVideos_LblFilterByLang {
            get {
                return ResourceManager.GetString("dlgHelpVideos_LblFilterByLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which video you would like to watch :.
        /// </summary>
        internal static string dlgHelpVideos_LblSelectVideos {
            get {
                return ResourceManager.GetString("dlgHelpVideos_LblSelectVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Comment..
        /// </summary>
        internal static string dlgHelpVideos_NoComment {
            get {
                return ResourceManager.GetString("dlgHelpVideos_NoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinovea - Watch a Video Tutorial..
        /// </summary>
        internal static string dlgHelpVideos_Title {
            get {
                return ResourceManager.GetString("dlgHelpVideos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        internal static string dlgHelpVideos_Watch {
            get {
                return ResourceManager.GetString("dlgHelpVideos_Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        internal static string dlgOpenFile_Filter {
            get {
                return ResourceManager.GetString("dlgOpenFile_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Video File.
        /// </summary>
        internal static string dlgOpenFile_Title {
            get {
                return ResourceManager.GetString("dlgOpenFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawings.
        /// </summary>
        internal static string dlgPreferences_btnDrawings {
            get {
                return ResourceManager.GetString("dlgPreferences_btnDrawings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string dlgPreferences_ButtonGeneral {
            get {
                return ResourceManager.GetString("dlgPreferences_ButtonGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play / Analyze.
        /// </summary>
        internal static string dlgPreferences_ButtonPlayAnalyze {
            get {
                return ResourceManager.GetString("dlgPreferences_ButtonPlayAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show drawings when video is playing.
        /// </summary>
        internal static string dlgPreferences_chkDrawOnPlay {
            get {
                return ResourceManager.GetString("dlgPreferences_chkDrawOnPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable persistence.
        /// </summary>
        internal static string dlgPreferences_chkEnablePersistence {
            get {
                return ResourceManager.GetString("dlgPreferences_chkEnablePersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch To Analysis Mode.
        /// </summary>
        internal static string dlgPreferences_GroupAnalysisMode {
            get {
                return ResourceManager.GetString("dlgPreferences_GroupAnalysisMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string dlgPreferences_GroupColors {
            get {
                return ResourceManager.GetString("dlgPreferences_GroupColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistence.
        /// </summary>
        internal static string dlgPreferences_grpPersistence {
            get {
                return ResourceManager.GetString("dlgPreferences_grpPersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid :.
        /// </summary>
        internal static string dlgPreferences_LabelGrid {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of files in history :.
        /// </summary>
        internal static string dlgPreferences_LabelHistoryCount {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelHistoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language :.
        /// </summary>
        internal static string dlgPreferences_LabelLanguages {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string dlgPreferences_LabelLogic {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Plane :.
        /// </summary>
        internal static string dlgPreferences_LabelPlane3D {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelPlane3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time markers format :.
        /// </summary>
        internal static string dlgPreferences_LabelTimeFormat {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Zone will take less than {0} MB of Memory..
        /// </summary>
        internal static string dlgPreferences_LabelWorkingZoneMemory {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelWorkingZoneMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Zone is less than {0} seconds..
        /// </summary>
        internal static string dlgPreferences_LabelWorkingZoneSeconds {
            get {
                return ResourceManager.GetString("dlgPreferences_LabelWorkingZoneSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, drawings will stay visible for {0} images around the Key Image..
        /// </summary>
        internal static string dlgPreferences_lblFading {
            get {
                return ResourceManager.GetString("dlgPreferences_lblFading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences....
        /// </summary>
        internal static string dlgPreferences_Title {
            get {
                return ResourceManager.GetString("dlgPreferences_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading User Interface... .
        /// </summary>
        internal static string dlgSplash_LoadInfos {
            get {
                return ResourceManager.GetString("dlgSplash_LoadInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Generic_Quit {
            get {
                return ResourceManager.GetString("Generic_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Generic_Save {
            get {
                return ResourceManager.GetString("Generic_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Kinovea....
        /// </summary>
        internal static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string mnuEdit {
            get {
                return ResourceManager.GetString("mnuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string mnuFile {
            get {
                return ResourceManager.GetString("mnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string mnuHelp {
            get {
                return ResourceManager.GetString("mnuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinovea Help....
        /// </summary>
        internal static string mnuHelpContents {
            get {
                return ResourceManager.GetString("mnuHelpContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        internal static string mnuHistory {
            get {
                return ResourceManager.GetString("mnuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset History.
        /// </summary>
        internal static string mnuHistoryReset {
            get {
                return ResourceManager.GetString("mnuHistoryReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string mnuImage {
            get {
                return ResourceManager.GetString("mnuImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string mnuLanguages {
            get {
                return ResourceManager.GetString("mnuLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion.
        /// </summary>
        internal static string mnuMotion {
            get {
                return ResourceManager.GetString("mnuMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Video File....
        /// </summary>
        internal static string mnuOpenFile {
            get {
                return ResourceManager.GetString("mnuOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string mnuOptions {
            get {
                return ResourceManager.GetString("mnuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences....
        /// </summary>
        internal static string mnuPreferences {
            get {
                return ResourceManager.GetString("mnuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string mnuRedo {
            get {
                return ResourceManager.GetString("mnuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string mnuScreens {
            get {
                return ResourceManager.GetString("mnuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Explorer.
        /// </summary>
        internal static string mnuToggleFileExplorer {
            get {
                return ResourceManager.GetString("mnuToggleFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Tutorials....
        /// </summary>
        internal static string mnuTutorialVideos {
            get {
                return ResourceManager.GetString("mnuTutorialVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string mnuUndo {
            get {
                return ResourceManager.GetString("mnuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic (h:mm:ss:hundredth).
        /// </summary>
        internal static string TimeCodeFormat_Classic {
            get {
                return ResourceManager.GetString("TimeCodeFormat_Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames Numbers.
        /// </summary>
        internal static string TimeCodeFormat_Frames {
            get {
                return ResourceManager.GetString("TimeCodeFormat_Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundredth of a minute.
        /// </summary>
        internal static string TimeCodeFormat_HundredthOfMinutes {
            get {
                return ResourceManager.GetString("TimeCodeFormat_HundredthOfMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten thousandth of an hour.
        /// </summary>
        internal static string TimeCodeFormat_TenThousandthOfHours {
            get {
                return ResourceManager.GetString("TimeCodeFormat_TenThousandthOfHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamps.
        /// </summary>
        internal static string TimeCodeFormat_Timestamps {
            get {
                return ResourceManager.GetString("TimeCodeFormat_Timestamps", resourceCulture);
            }
        }
    }
}
