//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinovea.ScreenManager.Properties
{
	using System;
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources
	{
		private static global::System.Resources.ResourceManager resourceMan;
		private static global::System.Globalization.CultureInfo resourceCulture;
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources()
		{
		}
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kinovea.ScreenManager.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}
		internal static System.Drawing.Bitmap activepencil
		{
			get
			{
				object obj = ResourceManager.GetObject("activepencil", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap angle5
		{
			get
			{
				object obj = ResourceManager.GetObject("angle5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap camerasingle
		{
			get
			{
				object obj = ResourceManager.GetObject("camerasingle", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap capture_settings5
		{
			get
			{
				object obj = ResourceManager.GetObject("capture_settings5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap capturedock3
		{
			get
			{
				object obj = ResourceManager.GetObject("capturedock3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap capturegrab5
		{
			get
			{
				object obj = ResourceManager.GetObject("capturegrab5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap capturepause5
		{
			get
			{
				object obj = ResourceManager.GetObject("capturepause5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap chrono5
		{
			get
			{
				object obj = ResourceManager.GetObject("chrono5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap close15x15
		{
			get
			{
				object obj = ResourceManager.GetObject("close15x15", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap closegrey
		{
			get
			{
				object obj = ResourceManager.GetObject("closegrey", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap comment20x20
		{
			get
			{
				object obj = ResourceManager.GetObject("comment20x20", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap comments2
		{
			get
			{
				object obj = ResourceManager.GetObject("comments2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap control_rec
		{
			get
			{
				object obj = ResourceManager.GetObject("control_rec", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap control_recstop
		{
			get
			{
				object obj = ResourceManager.GetObject("control_recstop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap cross5
		{
			get
			{
				object obj = ResourceManager.GetObject("cross5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap diaporama
		{
			get
			{
				object obj = ResourceManager.GetObject("diaporama", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap dock16x16
		{
			get
			{
				object obj = ResourceManager.GetObject("dock16x16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap ExportDock5
		{
			get
			{
				object obj = ResourceManager.GetObject("ExportDock5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap filesave
		{
			get
			{
				object obj = ResourceManager.GetObject("filesave", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap film_save
		{
			get
			{
				object obj = ResourceManager.GetObject("film_save", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap folder
		{
			get
			{
				object obj = ResourceManager.GetObject("folder", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap folder_new
		{
			get
			{
				object obj = ResourceManager.GetObject("folder_new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap handclose24b
		{
			get
			{
				object obj = ResourceManager.GetObject("handclose24b", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap handlersetleft
		{
			get
			{
				object obj = ResourceManager.GetObject("handlersetleft", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap handlersetright
		{
			get
			{
				object obj = ResourceManager.GetObject("handlersetright", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap handopen24c
		{
			get
			{
				object obj = ResourceManager.GetObject("handopen24c", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap handtool
		{
			get
			{
				object obj = ResourceManager.GetObject("handtool", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap keyframesonly
		{
			get
			{
				object obj = ResourceManager.GetObject("keyframesonly", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap layout1
		{
			get
			{
				object obj = ResourceManager.GetObject("layout1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap layoutB
		{
			get
			{
				object obj = ResourceManager.GetObject("layoutB", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap layoutC2
		{
			get
			{
				object obj = ResourceManager.GetObject("layoutC2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap layoutD
		{
			get
			{
				object obj = ResourceManager.GetObject("layoutD", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap line6
		{
			get
			{
				object obj = ResourceManager.GetObject("line6", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqbackdock
		{
			get
			{
				object obj = ResourceManager.GetObject("liqbackdock", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqbumperleft
		{
			get
			{
				object obj = ResourceManager.GetObject("liqbumperleft", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqbumperright
		{
			get
			{
				object obj = ResourceManager.GetObject("liqbumperright", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqcursor
		{
			get
			{
				object obj = ResourceManager.GetObject("liqcursor", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqfirst7
		{
			get
			{
				object obj = ResourceManager.GetObject("liqfirst7", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqhandlerleft2
		{
			get
			{
				object obj = ResourceManager.GetObject("liqhandlerleft2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqhandlerright3
		{
			get
			{
				object obj = ResourceManager.GetObject("liqhandlerright3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqlast5
		{
			get
			{
				object obj = ResourceManager.GetObject("liqlast5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqmiddlebar
		{
			get
			{
				object obj = ResourceManager.GetObject("liqmiddlebar", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqnext6
		{
			get
			{
				object obj = ResourceManager.GetObject("liqnext6", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqpause6
		{
			get
			{
				object obj = ResourceManager.GetObject("liqpause6", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqplay16
		{
			get
			{
				object obj = ResourceManager.GetObject("liqplay16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqplay17
		{
			get
			{
				object obj = ResourceManager.GetObject("liqplay17", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqprev5
		{
			get
			{
				object obj = ResourceManager.GetObject("liqprev5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap liqsync3
		{
			get
			{
				object obj = ResourceManager.GetObject("liqsync3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap magnifier2
		{
			get
			{
				object obj = ResourceManager.GetObject("magnifier2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap magnifierActive2
		{
			get
			{
				object obj = ResourceManager.GetObject("magnifierActive2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap MenuFileNewIcon
		{
			get
			{
				object obj = ResourceManager.GetObject("MenuFileNewIcon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap missing3
		{
			get
			{
				object obj = ResourceManager.GetObject("missing3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap outward4
		{
			get
			{
				object obj = ResourceManager.GetObject("outward4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap pdfexport
		{
			get
			{
				object obj = ResourceManager.GetObject("pdfexport", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap picture_save
		{
			get
			{
				object obj = ResourceManager.GetObject("picture_save", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap plane4
		{
			get
			{
				object obj = ResourceManager.GetObject("plane4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap playmodeloop
		{
			get
			{
				object obj = ResourceManager.GetObject("playmodeloop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap playmodeonce
		{
			get
			{
				object obj = ResourceManager.GetObject("playmodeonce", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap primselec_locked3
		{
			get
			{
				object obj = ResourceManager.GetObject("primselec_locked3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap primselec_unlocked3
		{
			get
			{
				object obj = ResourceManager.GetObject("primselec_unlocked3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap record
		{
			get
			{
				object obj = ResourceManager.GetObject("record", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap resettimescale
		{
			get
			{
				object obj = ResourceManager.GetObject("resettimescale", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap resizer4
		{
			get
			{
				object obj = ResourceManager.GetObject("resizer4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap save_paused_video
		{
			get
			{
				object obj = ResourceManager.GetObject("save_paused_video", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap saveblended
		{
			get
			{
				object obj = ResourceManager.GetObject("saveblended", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap savedata
		{
			get
			{
				object obj = ResourceManager.GetObject("savedata", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap saveDynamicDiaporama
		{
			get
			{
				object obj = ResourceManager.GetObject("saveDynamicDiaporama", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap savemuxed
		{
			get
			{
				object obj = ResourceManager.GetObject("savemuxed", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap saveStaticDiaporama
		{
			get
			{
				object obj = ResourceManager.GetObject("saveStaticDiaporama", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap savevideo
		{
			get
			{
				object obj = ResourceManager.GetObject("savevideo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap snapmulti_1
		{
			get
			{
				object obj = ResourceManager.GetObject("snapmulti_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap snapsingle_1
		{
			get
			{
				object obj = ResourceManager.GetObject("snapsingle_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap SpeedTrkBack5
		{
			get
			{
				object obj = ResourceManager.GetObject("SpeedTrkBack5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap SpeedTrkCursor7
		{
			get
			{
				object obj = ResourceManager.GetObject("SpeedTrkCursor7", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap SpeedTrkDecrease2
		{
			get
			{
				object obj = ResourceManager.GetObject("SpeedTrkDecrease2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap SpeedTrkIncrease2
		{
			get
			{
				object obj = ResourceManager.GetObject("SpeedTrkIncrease2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap stop
		{
			get
			{
				object obj = ResourceManager.GetObject("stop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap swap4
		{
			get
			{
				object obj = ResourceManager.GetObject("swap4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap SwatchIcon3
		{
			get
			{
				object obj = ResourceManager.GetObject("SwatchIcon3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap sync5
		{
			get
			{
				object obj = ResourceManager.GetObject("sync5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap syncmerge
		{
			get
			{
				object obj = ResourceManager.GetObject("syncmerge", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap text_backcolor
		{
			get
			{
				object obj = ResourceManager.GetObject("text_backcolor", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap text_bold
		{
			get
			{
				object obj = ResourceManager.GetObject("text_bold", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap text_forecolor
		{
			get
			{
				object obj = ResourceManager.GetObject("text_forecolor", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap text_italic
		{
			get
			{
				object obj = ResourceManager.GetObject("text_italic", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap text_strikethrough
		{
			get
			{
				object obj = ResourceManager.GetObject("text_strikethrough", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap text_underline
		{
			get
			{
				object obj = ResourceManager.GetObject("text_underline", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap TextToolIcon
		{
			get
			{
				object obj = ResourceManager.GetObject("TextToolIcon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap trajconfall3
		{
			get
			{
				object obj = ResourceManager.GetObject("trajconfall3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap trajconffocus3
		{
			get
			{
				object obj = ResourceManager.GetObject("trajconffocus3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap trajconflabel3
		{
			get
			{
				object obj = ResourceManager.GetObject("trajconflabel3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap trajconfsetorigin
		{
			get
			{
				object obj = ResourceManager.GetObject("trajconfsetorigin", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap undock16x16
		{
			get
			{
				object obj = ResourceManager.GetObject("undock16x16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
