//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinovea.Camera.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CameraLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CameraLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kinovea.Camera.Languages.CameraLang", typeof(CameraLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string FormConfiguration_Auto {
            get {
                return ResourceManager.GetString("FormConfiguration_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device property pages.
        /// </summary>
        public static string FormConfiguration_DevicePropertyPages {
            get {
                return ResourceManager.GetString("FormConfiguration_DevicePropertyPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while trying to display the device property page for {0}..
        /// </summary>
        public static string FormConfiguration_DevicePropertyPages_Error {
            get {
                return ResourceManager.GetString("FormConfiguration_DevicePropertyPages_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable hardware compression.
        /// </summary>
        public static string FormConfiguration_EnableHardwareCompression {
            get {
                return ResourceManager.GetString("FormConfiguration_EnableHardwareCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable software demosaicing.
        /// </summary>
        public static string FormConfiguration_EnableSoftwareDemosaicing {
            get {
                return ResourceManager.GetString("FormConfiguration_EnableSoftwareDemosaicing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export device GenICam XML file.
        /// </summary>
        public static string FormConfiguration_ExportDeviceGenICamXMLFile {
            get {
                return ResourceManager.GetString("FormConfiguration_ExportDeviceGenICamXMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import parameters.
        /// </summary>
        public static string FormConfiguration_ImportParameters {
            get {
                return ResourceManager.GetString("FormConfiguration_ImportParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayer format conversion:.
        /// </summary>
        public static string FormConfiguration_Properties_BayerFormatConversion {
            get {
                return ResourceManager.GetString("FormConfiguration_Properties_BayerFormatConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure:.
        /// </summary>
        public static string FormConfiguration_Properties_Exposure {
            get {
                return ResourceManager.GetString("FormConfiguration_Properties_Exposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure (µs):.
        /// </summary>
        public static string FormConfiguration_Properties_ExposureMicro {
            get {
                return ResourceManager.GetString("FormConfiguration_Properties_ExposureMicro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus:.
        /// </summary>
        public static string FormConfiguration_Properties_Focus {
            get {
                return ResourceManager.GetString("FormConfiguration_Properties_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate:.
        /// </summary>
        public static string FormConfiguration_Properties_Framerate {
            get {
                return ResourceManager.GetString("FormConfiguration_Properties_Framerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain:.
        /// </summary>
        public static string FormConfiguration_Properties_Gain {
            get {
                return ResourceManager.GetString("FormConfiguration_Properties_Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string FormConfiguration_Properties_ImageHeight {
            get {
                return ResourceManager.GetString("FormConfiguration_Properties_ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size:.
        /// </summary>
        public static string FormConfiguration_Properties_ImageSize {
            get {
                return ResourceManager.GetString("FormConfiguration_Properties_ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string FormConfiguration_Properties_ImageWidth {
            get {
                return ResourceManager.GetString("FormConfiguration_Properties_ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream format:.
        /// </summary>
        public static string FormConfiguration_Properties_StreamFormat {
            get {
                return ResourceManager.GetString("FormConfiguration_Properties_StreamFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string FormConfiguration_Reconnect {
            get {
                return ResourceManager.GetString("FormConfiguration_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resulting framerate:.
        /// </summary>
        public static string FormConfiguration_ResultingFramerate {
            get {
                return ResourceManager.GetString("FormConfiguration_ResultingFramerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string FormConfiguration_Test {
            get {
                return ResourceManager.GetString("FormConfiguration_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera configuration.
        /// </summary>
        public static string FormConfiguration_Title {
            get {
                return ResourceManager.GetString("FormConfiguration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string FormConnectionWizard_Authentication {
            get {
                return ResourceManager.GetString("FormConnectionWizard_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string FormConnectionWizard_Format {
            get {
                return ResourceManager.GetString("FormConnectionWizard_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host (IP address).
        /// </summary>
        public static string FormConnectionWizard_Host {
            get {
                return ResourceManager.GetString("FormConnectionWizard_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string FormConnectionWizard_Network {
            get {
                return ResourceManager.GetString("FormConnectionWizard_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string FormConnectionWizard_Password {
            get {
                return ResourceManager.GetString("FormConnectionWizard_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string FormConnectionWizard_Port {
            get {
                return ResourceManager.GetString("FormConnectionWizard_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final URL.
        /// </summary>
        public static string FormConnectionWizard_URL {
            get {
                return ResourceManager.GetString("FormConnectionWizard_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string FormConnectionWizard_User {
            get {
                return ResourceManager.GetString("FormConnectionWizard_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the connection test..
        /// </summary>
        public static string FormHandshakeResult_Failure_Message {
            get {
                return ResourceManager.GetString("FormHandshakeResult_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection test failure.
        /// </summary>
        public static string FormHandshakeResult_Failure_Title {
            get {
                return ResourceManager.GetString("FormHandshakeResult_Failure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection test.
        /// </summary>
        public static string FormHandshakeResult_Title {
            get {
                return ResourceManager.GetString("FormHandshakeResult_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string FormIconPicker_Title {
            get {
                return ResourceManager.GetString("FormIconPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Generic_Apply {
            get {
                return ResourceManager.GetString("Generic_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
    }
}
