name: Build Kinovea

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  VERSION: 2026.1.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore Kinovea.VS2019.sln

    - name: Cache extra dependencies
      id: extra-deps-cache
      uses: actions/cache@v4
      with:
        path: Refs/FFmpeg
        key: ${{ runner.os }}-extra-deps-${{ hashFiles('Refs/get-dependencies.ps1') }}
    
    - name: Get extra dependencies
      if: steps.extra-deps-cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: ./Refs/get-dependencies.ps1
  
    - name: Build Solution
      run: msbuild Kinovea.VS2019.sln /p:Platform="x64" /p:Configuration=Release /p:AllowedReferenceRelatedFileExtensions=none

    - name: Prepare Portable build
      shell: pwsh
      run: |
        $appData = "Kinovea/bin/x64/Release/AppData"
        New-Item -ItemType Directory -Force -Path $appData | Out-Null
        New-Item -ItemType File -Force -Path "$appData/portable" | Out-Null
        
    - name: Create Portable Archive
      shell: pwsh
      run: |
        Compress-Archive `
          -Path "Kinovea/bin/x64/Release/*" `
          -DestinationPath "Kinovea-Portable-${{env.VERSION}}.zip"
        
    - name: Upload Portable
      uses: actions/upload-artifact@v6
      with:
        name: Kinovea-Portable-${{env.VERSION}}
        path: Kinovea-Portable-${{env.VERSION}}.zip
        
    - name: Remove Portable AppData Folder
      shell: pwsh
      run: Remove-Item -Recurse -Force "Kinovea/bin/x64/Release/AppData"
          
    - name: Install NSIS
      uses: repolevedavaj/install-nsis@v1.2.0
      with:
        nsis-version: '3.11'
        
    - name: Make Installer
      shell: cmd
      run: makensis Installer\Kinovea.nsi
      
    - name: Upload Installer
      id: upload-installer
      uses: actions/upload-artifact@v6
      with:
        name: Kinovea-Installer-${{env.VERSION}}
        path: Installer/Kinovea-${{env.VERSION}}.exe


