name: Build Kinovea

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  VERSION: 2025.2

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore Kinovea.VS2019.sln

    - name: Build Solution
      run: msbuild Kinovea.VS2019.sln /p:Platform="x64" /p:Configuration=Release /p:AllowedReferenceRelatedFileExtensions=none

    - name: Upload Portable
      id: upload-portable
      uses: actions/upload-artifact@v6
      with:
        name: Kinovea-${{env.VERSION}}
        path: Kinovea/bin/x64/Release/
        
