name: Kinovea Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-2019  # Using Windows 2019 for better compatibility with .NET Framework 4.8
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup Visual Studio components
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[16.11,16.12)'  # VS 2019
        vs-prerelease: false
    
    - name: Setup .NET Framework
      uses: microsoft/setup-dotnet@v3
      with:
        dotnet-version: '4.8.x'
    
    - name: Install Visual Studio components
      shell: powershell
      run: |
        # Install VS components using vsconfig
        $vsconfig = @{
          "version" = "1.0"
          "components" = @(
            "Microsoft.VisualStudio.Component.Desktop.Development",
            "Microsoft.Net.Component.4.8.SDK",
            "Microsoft.VisualStudio.Component.Windows.Desktop",
            "Microsoft.VisualStudio.Component.VC.CLI.Support",
            "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core"
          )
        }
        $vsconfig | ConvertTo-Json | Out-File ".vsconfig"
        
        # Install components using VS installer
        Start-Process -Wait -FilePath "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" `
          -ArgumentList "modify --installPath ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"" --quiet --norestart --includeRecommended --config .vsconfig"
    
    - name: Restore NuGet packages
      run: nuget restore Kinovea.sln
    
    - name: Build Solution
      run: |
        msbuild /p:Configuration=Release /p:Platform="Any CPU" Kinovea.sln
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Kinovea-build
        path: |
          **/bin/Release/*.exe
          **/bin/Release/*.dll
          **/bin/Release/*.config
